# -*- coding: utf-8 -*-
"""3dnca_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGcbaLrbWbSfNiL6bhrwI2kj6kOZxMxq
"""

# Commented out IPython magic to ensure Python compatibility.
# %rm -rf 3d-nca
!git clone https://github.com/rm-a0/3d-nca --quiet
# %cd 3d-nca
!pip install torch numpy matplotlib pyvista -q

from google.colab import drive
drive.mount('/content/drive')

import os
import subprocess

import matplotlib.pyplot as plt
import numpy as np
import torch

import sys
sys.path.insert(0, '/content/3d-nca')

from nca3d.core.runners import MorphRunner
from nca3d.core.nca_model import NCAModel, NCAConfig
from nca3d.server.logger import NCALogger
from nca3d.viz.volume_mpl import show_volume_rgba_mpl, show_state_target_comparison_mpl

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")
if device == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")
    print(f"VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

TOTAL_EPOCHS = 4_000
PLOT_EVERY = 500
DRIVE_DIR = "/content/drive/MyDrive/nca_02"
TARGET_NPZ = "/content/drive/MyDrive/nca_02/target.npz"
os.makedirs(DRIVE_DIR, exist_ok=True)

if not os.path.exists(TARGET_NPZ):
    raise FileNotFoundError(f"Target NPZ not found: {TARGET_NPZ}")

with np.load(TARGET_NPZ, allow_pickle=True) as data:
    if "target" not in data:
        raise KeyError("NPZ file must contain 'target' array")
    target = data["target"].astype(np.float32)

if target.ndim != 4:
    raise ValueError(f"Expected target shape (D,H,W,C), got {target.shape}")
if target.shape[-1] != 4:
    raise ValueError(
        f"Expected RGBA target with 4 channels, got {target.shape[-1]}. "
        "Export with visible channels set to RGBA in Blender."
    )

GRID_SIZE = tuple(int(x) for x in target.shape[:3])

print(f"Target loaded : {TARGET_NPZ}")
print(f"Target grid   : {GRID_SIZE}")
print(f"Target voxels : {int((target[..., 3] > 0.15).sum())}")

plt.rcParams.update({
    "figure.dpi": 130,
    "font.size": 9,
    "axes.titlesize": 10,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "grid.alpha": 0.3,
})

fig = plt.figure(figsize=(5, 5))
ax = fig.add_subplot(111, projection="3d")
show_volume_rgba_mpl(
    target,
    title="Target before training",
    ax=ax,
    threshold=0.15,
    surface_only=True,
    point_size=14,
    view_angle=(28, 40),
    show=False,
)
plt.tight_layout()
target_plot_path = f"{DRIVE_DIR}/target_before_training.png"
fig.savefig(target_plot_path, dpi=150, bbox_inches="tight")
plt.show()
print(f"Target figure saved -> {target_plot_path}")

config = {
    "cell": {
        "hidden_channels": 16,
        "visible_channels": int(target.shape[-1]),
        "alive_threshold": 0.1,
        "task_channels": 0,
        "pos_channels": 3,
    },
    "perception": {
        "kernel_radius": 1,
        "channel_groups": 5,
    },
    "update": {
        "hidden_dim": 96,
        "stochastic_update": False,
        "fire_rate": 0.5,
    },
    "grid": {
        "size": GRID_SIZE,
    },
    "training": {
        "learning_rate": 2e-3,
        "num_epochs": TOTAL_EPOCHS,
        "batch_size": 4,
    },
}

logger = NCALogger(base_dir=DRIVE_DIR, checkpoint_interval=500)
logger.log_meta(config)
print(f"Run directory : {logger.run_dir}")

runner = MorphRunner(verbose=False)
runner.init(config, target)

total_params = sum(p.numel() for p in runner.model.parameters() if p.requires_grad)
print(f"\nMorphRunner ready")
print(f"  Total channels : {runner._cell_cfg.total_channels}  "
      f"(hidden={runner._cell_cfg.hidden_channels}, "
      f"visible={runner._cell_cfg.visible_channels})")
print(f"  Trainable params: {total_params:,}")
print(f"  Epochs          : {TOTAL_EPOCHS}")
print(f"  Device          : {device}")
print()

for metrics in runner.train():
    epoch = runner.current_epoch

    logger.log_epoch(
        epoch=epoch,
        loss_alpha=metrics["loss_alpha"],
        loss_color=metrics["loss_color"],
        loss_overflow=metrics["loss_overflow"],
        loss_total=metrics["loss_total"],
        model=runner.model,
        is_final=(epoch == TOTAL_EPOCHS),
    )

    if epoch % 200 == 0:
        print(f"  {epoch:>5}/{TOTAL_EPOCHS}  "
              f"loss={metrics['loss_total']:.5f}  "
              f"a={metrics['loss_alpha']:.5f}  "
              f"col={metrics['loss_color']:.5f}")

    if epoch % PLOT_EVERY == 0 or epoch == TOTAL_EPOCHS:
        show_state_target_comparison_mpl(
            state=runner.state.detach().cpu(),
            target=target,
            visible_channels=config["cell"]["visible_channels"],
            threshold=0.20,
            surface_only=True,
            point_size=14,
            title_prefix=f"Epoch {epoch} - ",
            view_angle=(28, 40),
            show=False,
        )
        cmp_path = f"{logger.run_dir}/comparison_ep{epoch:05d}.png"
        plt.gcf().savefig(cmp_path, dpi=150, bbox_inches="tight")
        plt.show()
        print(f"Comparison saved -> {cmp_path}")

print("\nTraining complete.")

loss_plot_path = f"{logger.run_dir}/plot_loss.png"
subprocess.run(
    [
        "python",
        "/content/3d-nca/scripts/plot_loss.py",
        "--run", logger.run_id,
        "--base-dir", DRIVE_DIR,
        "--out", loss_plot_path,
    ],
    check=True,
)

img = plt.imread(loss_plot_path)
plt.figure(figsize=(12, 6))
plt.imshow(img)
plt.axis("off")
plt.title(f"Loss curve - run {logger.run_id}")
plt.show()
print(f"Loss curve saved -> {loss_plot_path}")

nca_cfg = NCAConfig(
    grid_size=tuple(config["grid"]["size"]),
    hidden_channels=config["cell"]["hidden_channels"],
    visible_channels=config["cell"]["visible_channels"],
    task_channels=config["cell"]["task_channels"],
    pos_channels=config["cell"]["pos_channels"],
    alive_threshold=config["cell"]["alive_threshold"],
    perception_kernel_radius=config["perception"]["kernel_radius"],
    perception_channel_groups=config["perception"]["channel_groups"],
    update_hidden_dim=config["update"]["hidden_dim"],
    update_stochastic=config["update"]["stochastic_update"],
    update_fire_rate=config["update"]["fire_rate"],
)

nca_model = NCAModel(nca_cfg)
nca_model.grid.load_state_dict(runner.model.state_dict())

save_path = f"{DRIVE_DIR}/model_final_run{logger.run_id}.pt"
nca_model.save(save_path)
print(f"\nFinal NCAModel saved -> {save_path}")