# -*- coding: utf-8 -*-
"""3dnca_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZwd5Kz7feaTVBbtvKa_SeqlCK3bYNfF
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/rm-a0/3d-nca
# %cd 3d-nca

from google.colab import drive
drive.mount('/content/drive')

!pip install torch numpy pyngrok -q

import torch
print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")
print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2), "GB")

from pyngrok import ngrok

NGROK_TOKEN = "use-your-own-token"
ngrok.set_auth_token(NGROK_TOKEN)

# Kill any existing tunnels from previous runs
ngrok.kill()

tunnel = ngrok.connect(5555, "tcp")
public = tunnel.public_url.replace("tcp://", "")
host, port = public.split(":")

print("=" * 40)
print(f"  Host : {host}")
print(f"  Port : {port}")
print("=" * 40)

import sys
sys.path.insert(0, '/content/3d-nca')

from nca3d.server.app import main
main()