# -*- coding: utf-8 -*-
"""3dnca_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGcbaLrbWbSfNiL6bhrwI2kj6kOZxMxq
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/rm-a0/3d-nca
# %cd 3d-nca
!git checkout feature/logger
!pip install torch numpy -q

from google.colab import drive
drive.mount('/content/drive')

import torch
print("CUDA:", torch.cuda.is_available(),
      torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU")

import numpy as np

GRID = 32  # voxel grid size

def _rgba(mask: np.ndarray, r=1.0, g=1.0, b=1.0) -> np.ndarray:
    """Convert a (D,H,W) mask to (D,H,W,4) RGBA."""
    t = np.zeros((*mask.shape, 4), dtype=np.float32)
    t[mask, 0] = r
    t[mask, 1] = g
    t[mask, 2] = b
    t[mask, 3] = 1.0  # alpha = alive
    return t

def make_tetrahedron(grid: int = GRID, pad: int = 2) -> np.ndarray:
    """Create a solid regular tetrahedron target."""
    n = grid - 2 * pad
    i, j, k = np.mgrid[0:n, 0:n, 0:n]

    # Centered coordinates in [-1, 1] for a symmetric tetrahedron.
    x = ((i + 0.5) / n) * 2.0 - 1.0
    y = ((j + 0.5) / n) * 2.0 - 1.0
    z = ((k + 0.5) / n) * 2.0 - 1.0
    s = 0.72

    mask_raw = (
        (x + y + z <= s)
        & (-x - y + z <= s)
        & (-x + y - z <= s)
        & (x - y - z <= s)
    )
    full = np.zeros((grid, grid, grid), dtype=bool)
    full[pad : pad + n, pad : pad + n, pad : pad + n] = mask_raw
    return _rgba(full, r=0.3, g=0.5, b=1.0)

def make_cube(grid: int = GRID, pad: int = 4) -> np.ndarray:
    """Create a solid centered cube target."""
    full = np.zeros((grid, grid, grid), dtype=bool)
    full[pad : grid - pad, pad : grid - pad, pad : grid - pad] = True
    return _rgba(full, r=1.0, g=0.6, b=0.2)

def make_sphere(grid: int = GRID) -> np.ndarray:
    """Create a solid centered sphere target."""
    cx = cy = cz = grid / 2.0
    r = grid / 2.0 - 1.5
    i, j, k = np.mgrid[0:grid, 0:grid, 0:grid]
    mask = (i - cx) ** 2 + (j - cy) ** 2 + (k - cz) ** 2 <= r**2
    return _rgba(mask, r=0.2, g=0.9, b=0.4)

target_triangle = make_tetrahedron()
target_cube = make_cube()
target_sphere = make_sphere()

print("Shapes - alive voxels:")
for name, t in [("tetrahedron", target_triangle),
                ("cube", target_cube),
                ("sphere", target_sphere)]:
    print(f"  {name}: {int((t[..., 3] > 0).sum())}")

TOTAL_EPOCHS = 6000
SWITCH_1 = 2000  # tetrahedron -> cube
SWITCH_2 = 4000  # cube -> sphere

config = {
    "cell": {
        "hidden_channels": 16,
        "visible_channels": 4,  # RGBA
        "alive_threshold": 0.1,
    },
    "perception": {
        "kernel_radius": 1,
        "channel_groups": 3,
    },
    "update": {
        "hidden_dim": 96,
        "stochastic_update": False,
        "fire_rate": 0.5,
    },
    "grid": {
        "size": (GRID, GRID, GRID),
    },
    "training": {
        "learning_rate": 2e-3,
        "num_epochs": TOTAL_EPOCHS,
        "batch_size": 4,
    },
}

import sys
sys.path.insert(0, '/content/3d-nca')

from src.server.schedule import Event, EventType

schedule_events = [
    Event(epoch=SWITCH_1, event_type=EventType.TARGET_CHANGE,
          value=0.0, target=target_cube),
    Event(epoch=SWITCH_2, event_type=EventType.TARGET_CHANGE,
          value=0.0, target=target_sphere),
    # optional: ease off LR when switching targets so the model doesn't thrash
    Event(epoch=SWITCH_1, event_type=EventType.LEARNING_RATE, value=5e-4),
    Event(epoch=SWITCH_2, event_type=EventType.LEARNING_RATE, value=2e-4),
]



import os
from src.server.trainer import NCATrainer

LOG_DIR = "/content/drive/MyDrive/nca_morph"
os.makedirs(LOG_DIR, exist_ok=True)

loss_log = []

def send_fn(msg):
    """Log trainer state updates."""
    if msg.get("type") == "state":
        epoch = msg["epoch"]
        loss = msg["loss"]
        loss_log.append((epoch, loss))
        if epoch % 100 == 0:
            print(f"  epoch {epoch:>4}/{TOTAL_EPOCHS}  loss={loss:.5f}")
            # save state snapshot to Drive every 100 epochs
            import json

            path = f"{LOG_DIR}/state_epoch_{epoch:04d}.json"
            with open(path, "w") as f:
                json.dump({"epoch": epoch, "loss": loss,
                           "shape": msg["shape"], "data": msg["data"]}, f)

trainer = NCATrainer()
trainer.init(config, target_triangle, send_fn)

# Inject schedule directly (bypasses the socket message path)
trainer._schedule.replace(schedule_events)

print("Training started - tetrahedron -> cube -> sphere")
print(f"  Switch 1 at epoch {SWITCH_1}, Switch 2 at epoch {SWITCH_2}")

# Block until the background thread finishes
trainer._train_thread.join()

print("Training complete.")

import matplotlib.pyplot as plt

epochs, losses = zip(*loss_log) if loss_log else ([], [])
fig, ax = plt.subplots(figsize=(10, 3))
ax.plot(epochs, losses, lw=0.8, color="#378ADD")
for sw, label in [(SWITCH_1, "-> cube"), (SWITCH_2, "-> sphere")]:
    ax.axvline(sw, color="#D85A30", lw=1, linestyle="--")
    ax.text(sw + 20, ax.get_ylim()[1] * 0.9, label,
            color="#D85A30", fontsize=9)
ax.set_xlabel("Epoch")
ax.set_ylabel("Loss")
ax.set_title("NCA morph training - tetrahedron -> cube -> sphere")
plt.tight_layout()
plt.savefig(f"{LOG_DIR}/loss_curve.png", dpi=120)
plt.show()

!pip install pyvista

import json, base64, numpy as np, torch
from src.viz.volume_mpl import show_volume_alpha_mpl

with open(f"{LOG_DIR}/state_epoch_5000.json") as f:
    snap = json.load(f)

arr = np.frombuffer(base64.b64decode(snap["data"]),
                    dtype=np.float32).reshape(snap["shape"])
state_t = torch.from_numpy(arr)          # (1, C, D, H, W)
show_volume_alpha_mpl(state_t, title="Morph", point_size=40)