# -*- coding: utf-8 -*-
"""metamorphogenesis_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz3NxDP4HysJurDGKi2SWTSFwejIWIxy
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/rm-a0/3d-nca --quiet
# %cd 3d-nca
!pip install torch numpy pandas matplotlib -q

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import dataclasses
from pathlib import Path
from typing import Any, Dict, Generator, List, Optional

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import pandas as pd
from torch import Tensor

import sys
sys.path.insert(0, '/content/3d-nca')

from src.core.cell       import CellConfig
from src.core.grid       import Grid3D, GridConfig
from src.core.perception import PerceptionConfig
from src.core.schedule   import Schedule
from src.core.update     import UpdateConfig
from src.core.runners.base import NCARunner, TrainingSnapshot
from src.core.nca_model  import NCAModel, NCAConfig
from src.server.logger   import NCALogger
from src.viz.volume_mpl import show_volume_rgba_mpl, show_state_rgba_mpl

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")
if device == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")
    print(f"VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

GRID         = 32
TOTAL_EPOCHS = 6_000
DRIVE_DIR    = "/content/drive/MyDrive/nca_morph"
os.makedirs(DRIVE_DIR, exist_ok=True)

def _rgba(mask: np.ndarray, r: float, g: float, b: float) -> np.ndarray:
    """Boolean (D,H,W) mask -> (D,H,W,4) RGBA float32. Alpha = filled voxel."""
    out = np.zeros((*mask.shape, 4), dtype=np.float32)
    out[mask, 0] = r
    out[mask, 1] = g
    out[mask, 2] = b
    out[mask, 3] = 1.0
    return out

def make_tetrahedron(grid: int = GRID, pad: int = 3) -> np.ndarray:
    """Regular tetrahedron inscribed in the unit cube."""
    n = grid - 2 * pad
    i, j, k = np.mgrid[0:n, 0:n, 0:n]
    x = ((i + 0.5) / n) * 2.0 - 1.0
    y = ((j + 0.5) / n) * 2.0 - 1.0
    z = ((k + 0.5) / n) * 2.0 - 1.0
    s = 0.85
    mask_raw = (
          (x + y + z <= s)
        & (-x - y + z <= s)
        & (-x + y - z <= s)
        & ( x - y - z <= s)
    )
    full = np.zeros((grid, grid, grid), dtype=bool)
    full[pad : pad + n, pad : pad + n, pad : pad + n] = mask_raw
    return _rgba(full, r=0.35, g=0.55, b=1.0)

def make_cube(grid: int = GRID, pad: int = 5) -> np.ndarray:
    """Solid axis-aligned cube centred in the grid."""
    full = np.zeros((grid, grid, grid), dtype=bool)
    full[pad : grid - pad, pad : grid - pad, pad : grid - pad] = True
    return _rgba(full, r=1.0, g=0.6, b=0.2)


def make_sphere(grid: int = GRID) -> np.ndarray:
    """Solid sphere centred in the grid."""
    cx = cy = cz = grid / 2.0
    r  = grid / 2.0 - 2.0
    i, j, k = np.mgrid[0:grid, 0:grid, 0:grid]
    mask = (i - cx) ** 2 + (j - cy) ** 2 + (k - cz) ** 2 <= r ** 2
    return _rgba(mask, r=0.2, g=0.9, b=0.4)

target_tetra  = make_tetrahedron()
target_cube   = make_cube()
target_sphere = make_sphere()

TARGETS    = [target_tetra, target_cube, target_sphere]
TASK_NAMES = ["Tetrahedron", "Cube", "Sphere"]
N_TASKS    = len(TARGETS)

print("Target voxel counts:")
for name, t in zip(TASK_NAMES, TARGETS):
    print(f"  {name:12s}: {int((t[..., 3] > 0).sum()):>5} alive voxels")

plt.rcParams.update({
    "figure.dpi":       130,
    "font.size":        9,
    "axes.titlesize":   10,
    "figure.facecolor": "white",
    "axes.facecolor":   "white",
    "grid.alpha":       0.3,
})

fig, axes = plt.subplots(
    1, 3, figsize=(13, 5), subplot_kw={"projection": "3d"}
)
for col, (rgba, name) in enumerate(zip(TARGETS, TASK_NAMES)):
    show_volume_rgba_mpl(
        rgba,
        title=f"Target — {name}",
        ax=axes[col],
        surface_only=True,
        threshold=0.15,
        point_size=14,
        view_angle=(28, 40),
        show=False,
    )
fig.suptitle("Training targets  (surface voxels only)", fontsize=12, y=1.0)
plt.tight_layout()
plt.savefig(f"{DRIVE_DIR}/targets.png", dpi=150, bbox_inches="tight")
plt.show()
print("Targets visualisation saved to Drive.")

config = {
    "cell": {
        "hidden_channels":  16,
        "visible_channels": 4, # RGBA
        "alive_threshold":  0.1,
        "task_channels":    N_TASKS, # 3 - one per shape
        "pos_channels":     3,
    },
    "perception": {
        "kernel_radius":  1,
        "channel_groups": 5,
    },
    "update": {
        "hidden_dim":        96,
        "stochastic_update": False,
        "fire_rate":         0.5,
    },
    "grid": {
        "size": (GRID, GRID, GRID),
    },
    "training": {
        "learning_rate": 2e-3,
        "num_epochs":    TOTAL_EPOCHS,
        "batch_size":    4,
    },
}

_POOL_SIZE        = 32
_STEP_MIN_START   =  8
_STEP_MIN_END     = 32
_STEP_MAX_START   = 16
_STEP_MAX_END     = 64
_CURRICULUM_EPOCHS = 2_000


class MultiTaskMorphRunner(NCARunner):
    """Pool runner for task-conditioned 3D-NCA metamorphogenesis."""

    def __init__(self, verbose: bool = True) -> None:
        self.verbose          = verbose
        self.model: Optional[Grid3D] = None
        self.optimizer        = None
        self.targets: List[Tensor] = []
        self.state: Optional[Tensor] = None
        self.current_epoch    = 0
        self.total_epochs     = 0
        self.latest_loss      = 0.0
        self._cell_cfg: Optional[CellConfig] = None
        self._device: Optional[str] = None
        self._pool: List[Tensor] = []
        self._pool_tasks: List[int] = []   # task id per pool slot
        self._batch_size      = 4
        self._lr_scheduler    = None
        self._latest_metrics: Dict[str, float] = {}

    # ── NCARunner interface ───────────────────────────────────────────────────

    def init(self, config: dict, target: "np.ndarray | List[np.ndarray]") -> None:
        if not isinstance(target, list):
            target = [target]
        n = len(target)

        # Patch task_channels into cell config
        cell_cfg_d = {**config["cell"], "task_channels": n}
        self._cell_cfg   = CellConfig(**cell_cfg_d)
        perc_cfg         = PerceptionConfig(**config["perception"])
        upd_cfg          = UpdateConfig(**config["update"])
        grid_cfg         = GridConfig(**config["grid"])
        self._device     = "cuda" if torch.cuda.is_available() else "cpu"

        self.model = Grid3D(
            self._cell_cfg, perc_cfg, upd_cfg, grid_cfg
        ).to(self._device)

        self.optimizer = torch.optim.AdamW(
            self.model.parameters(),
            lr=config["training"]["learning_rate"],
            weight_decay=1e-5,
        )
        self._lr_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer,
            T_max=config["training"]["num_epochs"],
            eta_min=1e-5,
        )

        vis = self._cell_cfg.visible_channels
        self.targets = [self._prep(t, vis) for t in target]

        # Balanced pool: each task gets approximately equal representation.
        self._pool, self._pool_tasks = [], []
        for i in range(_POOL_SIZE):
            tid    = i % n
            t_ids  = torch.tensor([tid], device=self._device)
            seed   = self.model.seed_center(1, self._device, t_ids)
            self._pool.append(seed)
            self._pool_tasks.append(tid)

        self.state         = self._pool[0]
        self.current_epoch = 0
        self.total_epochs  = config["training"]["num_epochs"]
        self._batch_size   = config["training"].get("batch_size", 4)
        self.latest_loss   = 0.0

    def train(
        self, schedule: Optional[Schedule] = None
    ) -> Generator[Dict[str, Any], None, None]:
        for epoch in range(1, self.total_epochs + 1):
            metrics            = self._step()
            self.current_epoch = epoch
            self.latest_loss   = metrics["loss_total"]
            self._latest_metrics = {
                k: float(v) for k, v in metrics.items()
                if isinstance(v, (int, float))
            }
            if schedule is not None:
                schedule.check_and_execute(epoch, self)
            yield metrics

    def snapshot(self) -> TrainingSnapshot:
        return TrainingSnapshot(
            state            = self.state.detach().cpu().numpy().astype(np.float32),
            epoch            = self.current_epoch,
            total_epochs     = self.total_epochs,
            loss             = self.latest_loss,
            visible_channels = self._cell_cfg.visible_channels,
            metrics          = dict(self._latest_metrics),
        )

    def set_target(self, target: Any) -> None:
        pass  # N/A — targets are fixed at init for multi-task training.

    # ── Internals ─────────────────────────────────────────────────────────────

    def _get_step_range(self) -> tuple:
        """Curriculum ramp: steps increase from (8,16) → (32,64) over 2000 epochs."""
        t  = min(self.current_epoch / max(_CURRICULUM_EPOCHS, 1), 1.0)
        lo = int(_STEP_MIN_START + t * (_STEP_MIN_END - _STEP_MIN_START))
        hi = int(_STEP_MAX_START + t * (_STEP_MAX_END - _STEP_MAX_START))
        return max(lo, 4), max(hi, lo + 1)

    def _step(self) -> Dict[str, Any]:
        dev      = self._device
        cell_cfg = self._cell_cfg
        vis      = cell_cfg.visible_channels
        bs       = min(len(self._pool), self._batch_size)
        lo, hi   = self._get_step_range()
        n_steps  = random.randint(lo, hi)

        # Sample a random batch from pool
        indices    = random.sample(range(len(self._pool)), bs)
        batch      = torch.cat([self._pool[i] for i in indices], dim=0)  # (B,C,D,H,W)
        task_ids_b = [self._pool_tasks[i] for i in indices]
        tgt_batch  = torch.cat(
            [self.targets[tid] for tid in task_ids_b], dim=0
        )  # (B,4,D,H,W)  — visible channels only

        # Replace worst sample (per-task MSE) with a fresh seed for that task
        with torch.no_grad():
            per_sample = [
                F.mse_loss(
                    batch[i : i + 1, -vis:],
                    self.targets[task_ids_b[i]][:, -vis:],
                ).item()
                for i in range(bs)
            ]
            worst      = int(np.argmax(per_sample))
            reset_task = torch.tensor([task_ids_b[worst]], device=dev)
            batch[worst : worst + 1] = self.model.seed_center(1, dev, reset_task)

        # Forward + loss
        self.optimizer.zero_grad()
        state    = self.model(batch, steps=n_steps)
        pred_vis = state[:, -vis:]
        tgt_vis  = tgt_batch[:, -vis:]
        pred_a   = pred_vis[:, -1:]
        tgt_a    = tgt_vis[:, -1:]
        tgt_mask = (tgt_a > cell_cfg.alive_threshold).float()

        loss_alpha    = F.mse_loss(pred_a, tgt_a)
        color_diff    = (pred_vis[:, :-1] - tgt_vis[:, :-1]) ** 2 * tgt_mask
        loss_color    = color_diff.sum() / tgt_mask.sum().clamp(min=1.0)
        loss_overflow = ((pred_a * (1.0 - tgt_mask)) ** 2).mean()

        loss = 4.0 * loss_alpha + 1.0 * loss_color + 2.0 * loss_overflow
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
        self.optimizer.step()
        self._lr_scheduler.step()

        # Write updated states back to pool
        with torch.no_grad():
            for j, idx in enumerate(indices):
                self._pool[idx] = state[j : j + 1].detach()
        self.state = state[0:1].detach()

        return {
            "loss_total":    loss.item(),
            "loss_alpha":    loss_alpha.item(),
            "loss_color":    loss_color.item(),
            "loss_overflow": loss_overflow.item(),
        }

    def _prep(self, t: np.ndarray, vis: int) -> Tensor:
        """(D,H,W,C) -> (1,C,D,H,W) on device. Visible channels only for loss."""
        t_chw = np.transpose(t, (3, 0, 1, 2)).astype(np.float32)
        return torch.from_numpy(t_chw).unsqueeze(0).to(self._device)

logger = NCALogger(base_dir=DRIVE_DIR, checkpoint_interval=500)

# Store effective config (task_channels patched) so checkpoints are reloadable
effective_config = {
    **config,
    "cell": {**config["cell"], "task_channels": N_TASKS},
}
logger.log_meta(effective_config)
print(f"Run directory : {logger.run_dir}")

runner = MultiTaskMorphRunner(verbose=False)
runner.init(config, TARGETS)

total_params = sum(p.numel() for p in runner.model.parameters() if p.requires_grad)
print(f"\nMultiTaskMorphRunner ready")
print(f"  Tasks          : {', '.join(TASK_NAMES)}")
print(f"  Total channels : {runner._cell_cfg.total_channels}  "
      f"(hidden={runner._cell_cfg.hidden_channels}, "
      f"task={runner._cell_cfg.task_channels}, "
      f"visible={runner._cell_cfg.visible_channels})")
print(f"  Trainable params: {total_params:,}")
print(f"  Epochs          : {TOTAL_EPOCHS}")
print(f"  Device          : {device}")
print()

for metrics in runner.train():
    epoch = runner.current_epoch

    # NCALogger handles: loss.csv append + checkpoint every 500 epochs + final
    logger.log_epoch(
        epoch         = epoch,
        loss_alpha    = metrics["loss_alpha"],
        loss_color    = metrics["loss_color"],
        loss_overflow = metrics["loss_overflow"],
        loss_total    = metrics["loss_total"],
        model         = runner.model,
        is_final      = (epoch == TOTAL_EPOCHS),
    )

    if epoch % 200 == 0:
        print(f"  {epoch:>5}/{TOTAL_EPOCHS}  "
              f"loss={metrics['loss_total']:.5f}  "
              f"α={metrics['loss_alpha']:.5f}  "
              f"col={metrics['loss_color']:.5f}")

print("\nTraining complete.")

df = pd.read_csv(logger._loss_path)

fig, ax = plt.subplots(figsize=(11, 3.8))
ax.semilogy(df["epoch"], df["loss_alpha"],    lw=0.9, color="#1f77b4", label="α loss")
ax.semilogy(df["epoch"], df["loss_color"],    lw=0.9, color="#ff7f0e", label="color loss")
ax.semilogy(df["epoch"], df["loss_overflow"], lw=0.9, color="#2ca02c", label="overflow loss")
ax.semilogy(df["epoch"], df["loss_total"],    lw=1.4, color="#d62728", label="total loss")
ax.set_xlabel("Epoch")
ax.set_ylabel("Loss (log scale)")
ax.set_title(
    f"Metamorphogenesis — task-conditioned 3D-NCA  "
    f"[run {logger.run_id},  {N_TASKS} shapes,  {TOTAL_EPOCHS} epochs]"
)
ax.legend(loc="upper right", fontsize=8, framealpha=0.7)
ax.grid(True, which="both", alpha=0.25)
fig.tight_layout()
fig.savefig(f"{logger.run_dir}/loss_curve.png", dpi=150)
plt.show()

INF_STEPS = 160
VIS       = config["cell"]["visible_channels"]

runner.model.eval()
inferred: Dict[str, Tensor] = {}

with torch.no_grad():
    for tid, name in enumerate(TASK_NAMES):
        t_ids = torch.tensor([tid], device=device)
        state = runner.model.seed_center(1, device, t_ids)
        for _ in range(INF_STEPS):
            state = runner.model(state, steps=1, use_checkpointing=False)
            state = torch.clamp(state, -1.0, 1.0)
        inferred[name] = state.cpu()
        alive = int((state[0, -1] > runner._cell_cfg.alive_threshold).sum().item())
        print(f"  {name:12s}: {alive:>5} alive voxels after {INF_STEPS} steps")

fig, axes = plt.subplots(
    2, N_TASKS,
    figsize=(13, 9),
    subplot_kw={"projection": "3d"},
)
row_labels = ["Target", "Model output"]

for col, name in enumerate(TASK_NAMES):
    # Row 0 — target
    show_volume_rgba_mpl(
        TARGETS[col],
        title=f"Target\n{name}",
        ax=axes[0, col],
        surface_only=True,
        threshold=0.15,
        point_size=14,
        view_angle=(28, 40),
        show=False,
    )
    # Row 1 — model output
    show_state_rgba_mpl(
        inferred[name],
        visible_channels=VIS,
        title=f"Model output\n{name}",
        ax=axes[1, col],
        surface_only=True,
        threshold=0.20,
        point_size=14,
        view_angle=(28, 40),
        show=False,
    )

# Row labels on the left
for row, label in enumerate(row_labels):
    axes[row, 0].text2D(
        -0.18, 0.5, label,
        transform=axes[row, 0].transAxes,
        fontsize=11, fontweight="bold",
        va="center", ha="right",
        rotation=90,
    )

fig.suptitle(
    f"Task-conditioned metamorphogenesis — 3D-NCA  [run {logger.run_id}]",
    fontsize=13, y=1.01,
)
plt.tight_layout()
fig.savefig(f"{logger.run_dir}/comparison.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"Comparison figure saved -> {logger.run_dir}/comparison.png")

nca_cfg = NCAConfig(
    grid_size                 = tuple(config["grid"]["size"]),
    hidden_channels           = config["cell"]["hidden_channels"],
    visible_channels          = config["cell"]["visible_channels"],
    task_channels             = config["cell"]["task_channels"],
    pos_channels              = config["cell"]["pos_channels"],
    alive_threshold           = config["cell"]["alive_threshold"],
    perception_kernel_radius  = config["perception"]["kernel_radius"],
    perception_channel_groups = config["perception"]["channel_groups"],
    update_hidden_dim         = config["update"]["hidden_dim"],
    update_stochastic         = config["update"]["stochastic_update"],
    update_fire_rate          = config["update"]["fire_rate"],
)

# Wrap trained Grid3D weights into NCAModel (state_dict keys are compatible)
nca_model = NCAModel(nca_cfg)
nca_model.grid.load_state_dict(runner.model.state_dict())

save_path = f"{DRIVE_DIR}/model_final_run{logger.run_id}.pt"
nca_model.save(save_path)
print(f"\nFinal NCAModel saved -> {save_path}")
print(f"Task mapping: { {i: name for i, name in enumerate(TASK_NAMES)} }")