# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpUEEdnOaqTAjT97qz3CnNQfRTlGzWkI
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/rm-a0/3d-nca --quiet
# %cd 3d-nca

from google.colab import drive
drive.mount('/content/drive')

!pip install torch numpy matplotlib pyvista -q

MODEL_PATH  = "/content/drive/MyDrive/nca_inf/model.pt"
TITLE       = "3D NCA - sphere growth from a single seed cell"
TOTAL_STEPS = 160
SNAP_STEPS  = [0, 10, 30, 60, 100, 160]
THRESHOLD   = 0.1

# Task id to seed with. 0 for single-task models or the first task.
# Change to 1 or 2 for multi-task metamorphogenesis models.
TASK_ID     = 0
SAVE_PATH   = "/content/drive/MyDrive/nca_inf/inference.png"

import sys
import torch
import matplotlib.pyplot as plt

sys.path.insert(0, '/content/3d-nca')

from src.core.cell import CellConfig
from src.core.grid import Grid3D, GridConfig
from src.core.nca_model import NCAModel
from src.core.perception import PerceptionConfig
from src.core.update import UpdateConfig
from src.viz.volume_mpl import show_state_rgba_mpl


def _normalize_grid_state_dict(state_dict: dict) -> dict:
    has_grid_prefix = any(k.startswith("grid.") for k in state_dict)
    if not has_grid_prefix:
        return state_dict
    return {(k[5:] if k.startswith("grid.") else k): v for k, v in state_dict.items()}


def load_inference_model(path: str, device: str):
    """Load either a final NCAModel file or a saved training checkpoint."""
    ckpt = torch.load(path, map_location=device, weights_only=False)
    config = ckpt.get("config")
    if not isinstance(config, dict):
        raise ValueError("Checkpoint must contain a dict 'config' field.")

    if "cell" in config and "grid" in config:
        cell_cfg = CellConfig(**config["cell"])
        perc_cfg = PerceptionConfig(**config.get("perception", {}))
        upd_cfg = UpdateConfig(**config.get("update", {}))
        grid_cfg = GridConfig(size=tuple(int(v) for v in config["grid"]["size"]))

        state_dict = ckpt.get("state_dict")
        if not isinstance(state_dict, dict):
            raise ValueError("Checkpoint is missing a valid 'state_dict' field.")

        model = Grid3D(cell_cfg, perc_cfg, upd_cfg, grid_cfg).to(device)
        model.load_state_dict(_normalize_grid_state_dict(state_dict), strict=True)
        info = {
            "format": "training checkpoint",
            "grid_size": grid_cfg.size,
            "visible_channels": cell_cfg.visible_channels,
            "task_channels": cell_cfg.task_channels,
            "pos_channels": cell_cfg.pos_channels,
            "total_channels": cell_cfg.total_channels,
        }
        return model, info

    # Fallback to NCAModel format for final exported models.
    model = NCAModel.load(path, device=device, strict=True)
    info = {
        "format": "final model",
        "grid_size": model.grid_size,
        "visible_channels": model.visible_channels,
        "task_channels": model.config.task_channels,
        "pos_channels": model.config.pos_channels,
        "total_channels": model.total_channels,
    }
    return model, info

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")

model, model_info = load_inference_model(MODEL_PATH, device=device)
model.eval()

n_tasks = model_info["task_channels"]
vis     = model_info["visible_channels"]
print(f"Model  : {MODEL_PATH}")
print(f"Format : {model_info['format']}")
print(f"Grid   : {model_info['grid_size']}  |  channels: {model_info['total_channels']}  "
    f"(vis={vis}, task={n_tasks}, pos={model_info['pos_channels']})")

assert max(SNAP_STEPS) <= TOTAL_STEPS, \
    f"SNAP_STEPS contains {max(SNAP_STEPS)} but TOTAL_STEPS is {TOTAL_STEPS}"

task_ids = torch.tensor([TASK_ID], device=device) if n_tasks > 0 else None
state    = model.seed_center(1, device, task_ids=task_ids)
frames   = {}
done     = 3

with torch.no_grad():
    for target_step in sorted(SNAP_STEPS):
        n = target_step - done
        if n > 0:
            state = model(state, steps=n, use_checkpointing=False)
            state = torch.clamp(state, -1.0, 1.0)
            done  = target_step
        frames[target_step] = state.cpu()

alive_final = int((frames[max(SNAP_STEPS)][0, -1] > THRESHOLD).sum())
print(f"Alive voxels at step {max(SNAP_STEPS)}: {alive_final}")

plt.rcParams.update({"figure.dpi": 130, "font.size": 9, "figure.facecolor": "white"})

n_snaps = len(SNAP_STEPS)
fig, axes = plt.subplots(
    1, n_snaps,
    figsize=(n_snaps * 2.6, 3.2),
    subplot_kw={"projection": "3d"},
)

for ax, step in zip(axes, SNAP_STEPS):
    show_state_rgba_mpl(
        frames[step],
        visible_channels = vis,
        threshold        = THRESHOLD,
        surface_only     = True,
        point_size       = 10,
        view_angle       = (28, 40),
        ax               = ax,
        show             = False,
        title            = "",
    )
    alive = int((frames[step][0, -1] > THRESHOLD).sum())
    ax.set_title(f"step {step}\n({alive} vx)", fontsize=8, pad=2)

fig.suptitle(TITLE, fontsize=11, y=1.02)
plt.tight_layout()

if SAVE_PATH:
    fig.savefig(SAVE_PATH, dpi=150, bbox_inches="tight")
    print(f"Saved -> {SAVE_PATH}")

plt.show()